services:
  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    ports:
    - 9092:29092
    - 7071:7071
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka-1
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent.jar=7071:/usr/share/jmx_exporter/kafka-broker.yml
    volumes:
    - ./jmx_exporter:/usr/share/jmx_exporter
    healthcheck:
      test:
      - CMD-SHELL
      - KAFKA_OPTS='' kafka-broker-api-versions --bootstrap-server localhost:9092
        || exit 1
      interval: 10s
      timeout: 3s
      retries: 30
      start_period: 30s
    networks:
    - kafka-network
  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    ports:
    - 9093:29092
    - 7072:7072
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_JMX_PORT: 9998
      KAFKA_JMX_HOSTNAME: kafka-2
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent.jar=7072:/usr/share/jmx_exporter/kafka-broker.yml
    volumes:
    - ./jmx_exporter:/usr/share/jmx_exporter
    healthcheck:
      test:
      - CMD-SHELL
      - KAFKA_OPTS='' kafka-broker-api-versions --bootstrap-server localhost:9092
        || exit 1
      interval: 10s
      timeout: 3s
      retries: 30
      start_period: 30s
    networks:
    - kafka-network
  kafka-3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-3
    ports:
    - 9094:29092
    - 7073:7073
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: kafka-3
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent.jar=7073:/usr/share/jmx_exporter/kafka-broker.yml
    volumes:
    - ./jmx_exporter:/usr/share/jmx_exporter
    healthcheck:
      test:
      - CMD-SHELL
      - KAFKA_OPTS='' kafka-broker-api-versions --bootstrap-server localhost:9092
        || exit 1
      interval: 10s
      timeout: 3s
      retries: 30
      start_period: 30s
    networks:
    - kafka-network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
    - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
    - kafka-1
    - kafka-2
    - kafka-3
    networks:
    - kafka-network
  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    ports:
    - 9308:9308
    command:
    - --kafka.server=kafka-1:9092
    - --kafka.server=kafka-2:9092
    - --kafka.server=kafka-3:9092
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    networks:
    - kafka-network
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    depends_on:
    - kafka-exporter
    networks:
    - kafka-network
  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
    - grafana-data:/var/lib/grafana
    depends_on:
    - prometheus
    networks:
    - kafka-network
networks:
  kafka-network:
    driver: bridge
volumes:
  prometheus-data: null
  grafana-data: null
